import {

  cdebug,chess,adapt,fifa,jam,techquiz,valo,b,m,p,t,a,w,v,l,s,c,j,h,i,f
  
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "heros",
    title: "heros",
  },
];



const technical = [
  {
    title: "Tech Quiz",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdgaTV_8WIB_etM1fxO9uRDD-llzkJ2NlFx8mbJ6WPe3asK1A/viewform?usp=sf_link",
    company_name: "Test your tech knowledge skills",
    icon: a,
    iconBg: "#fff",
    date: "04/10/2023 - 02:30 PM",
    points: [
      "A team can contain a maximum of three participants",
      "Consists of three rounds.",
      "A general technical quiz.",
      "Registration fee is Rs. 100/team.",
      "COORDINATORS: BARATH KUMAR.M (+91 63822 82725), LAKSHMI NARAYANA PERUMAL.S (+91 77083 94526), KAILASH.S (+91 6385 687 148), ARVIND.A +91 93610 80414)",
    ],
  },
  {
    title: "Technical connexion",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSfkddi7Q_C8-pb_ZQjryO0OdQqPH6o0GgzfUsnROKu-jXZfxQ/viewform?usp=sf_link",
    company_name: "Explore tech's impact through innovative connections",
    icon: t,
    iconBg: "#fff",
    date: "05/10/2023 - 11:00 AM",
    points: [
      "A team can consist of two members.",
      "Three Rounds will be Conducted. ",
      "First round : Written round. Second round: Questions will be displayed and the teams should answer it within 30 seconds.",
      "Third round:  Indirect clues will be given one by one and the teams should find the technical word behind it.",
      "Registration fee is Rs. 100/-.",
      "COORDINATORS: PARIMALA DEVI(8807342948), SHAMEER AHMED(6374636031), SATISH KUMAR(6383718465), PRAVEEN P(6385451354)",
    ],
  },
  {
    title: "Circuit Debugging",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSegjy9Vf1Iza4q_KdqNlomM05JaEvYNVt6s-TeIpHwChh5Phw/viewform?usp=sf_link",
    company_name: "Identify and fix electrical faults",
    icon: c,
    iconBg: "#fff",
    date: "04/10/2023 - 02:00 PM",
    points: [
      "A team can contain a maximum of three participants",
      "The event has three rounds which test your circuit debugging skills. ",
      "Prerequisite: basics of analog and digital electronics, op amp, ic555, multsim simulator.",
      "Registration fee is Rs. 150.",
      "COORDINATORS: Sree Teja (7989291343), kalaimathi (9345831705), Ganja Yuvarani (9493724523)",
    ],
  },
  {
    title: "Paper Presentation",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScAZBLjimWg2_LrF1JW193gFuUUCs1K98VQqKHQ5zaDcO9pxA/viewform?usp=sf_link",
    company_name: "Showcase research and ideas eloquently.",
    icon: p,
    iconBg: "#fff",
    date: "04/10/2023 - 10:00 AM",
    points: [
      "A team can contain a maximum of three participants",
      "The selected team should come with the hard copy of their abstracts ",
      "Presentation time is 10 to 15 minutes",
      "Registration fee is Rs. 50.",
      "COORDINATORS: ANURAGAA S (6381278692), THIRUMURUGAN S(9629701158), SWARUP(6309086433)",
    ],
  },
  {
    title: "Cinematic Science",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSeFolVc55n1jVilkikRmdO1Fa257bzr8X1ZHeT2uCTe9TDWVw/viewform?usp=sf_link",
    company_name: "Explore science through captivating cinematic experiences.",
    icon: c,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      " A team can consist of two members.",
      "A scene from a movie will be displayed and the participant has to find the scientific concept behind that particular scene and explain about it briefly.",
      "Registration fee is Rs. 100.",
      "COORDINATORS:VIJAYABARATHI J(6380436136), SIVAPRAKASH R(8300159749), TERENCE JONES",
    ],
  },
  {
    title: "Triad (Googler, Electric Fence,snippet shuffle)",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSf1HngbWA1kAhDGNP5qeYgM40H5_6j5YbjIJmDnrkE0yc70oQ/viewform?usp=sf_link",
    company_name: "Fun Fun Fun - Three ways",
    icon: t,
    iconBg: "#fff",
    date: "05/10/2023 - 02:00 PM",
    points: [
      "A team can consist of two members.",
      "It is a collection of three fun events.",
      "Part 1: GOOGLER, Part 2: SNIPPET SHUFFLE, Part 3: ELECTRIC FENCE",
      "Registration fee is Rs. 100/-",
      "COORDINATORS:  CH VENKATA UPENDRA(8985122204), YUVARANI V D(7695981434), SHEFAOUDEEN Z(9361030025), SHAANTHAPRIYAN B",
    ],
  },
  {
    title: "Programming dating",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdgaTV_8WIB_etM1fxO9uRDD-llzkJ2NlFx8mbJ6WPe3asK1A/viewform?usp=sf_link",
    company_name: "Where Love Meets Logic.",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 02:00 PM",
    points: [
      "A team can consist of two members.",
      "A female coder is partnered with a male programmer they have to go on programming date which should be technical..",
      "Registration fee is Rs. 150/team.",
      "COORDINATORS: SANGESH S(8870073053), MANJUNNATH, SIVABHARATH K",
    ],
  },
  {
    title: "Hunt the Code",
    link:"https://forms.gle/u56kqcYgeZ6vDEfb9",
    company_name: "A thrilling code-breaking adventure awaits!",
    icon: h,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Maximum of 2 members per team.",
      "The contest will consist of sets of questions, but with a catch: you will not be given the problem statement for any question. Just the sample inputs and sample outputs. Using just that, you are required to find the logic between the inputs and the outputs and code the program which can give the correct output for the given input. (There will also be hidden testcases)",
      "Registration fee is Rs. 75.",
      "COORDINATORS: T C Adityaa-9944581729, Keerthivasan-8778336814 , Kamalesh-9150431574",
    ],
  },
]

const nontechnical = [
  {
    title: "Chess",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdWN2qrHMj7DyiXgK2_SbjFtQrfnKmVTzUyr0L935hi5n9PTw/viewform?usp=sf_link",
    company_name: "Chess tournament for strategic minds.",
    icon: c,
    iconBg: "#fff",
    date: "04/10/2023 - 02:30 PM",
    points: [
      "Solo event. 1v1.",
      "There will be 10 mins time limit for each player. No increment for time after each move",
      "Every match will be elimination match",
      "If stalemate/draw occurs there will be tie breaker for each player with 5 mins each.",
      "The registration amount is Rs. 75 per member",
      "COORDINATORS: SAKTHIDHARSHAN M- 8220855421, MURALIDHARAN B-9047085058, HARIHARAN GV - 9629231402",
    ],
  },
  {
    title: "Series Quiz",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScvY0Spedrxdt9fqSIfzCIaFi8_KPZyd75THBie2u-hbhY-Sg/viewform?usp=sf_link",
    company_name: "Test your TV show knowledge and win prizes!",
    icon: s,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Maximum three and minimum two members per team are allowed",
      "Every participant must be respectful towards coordinators and other participants.",
      "Any unfair moments will lead you to disqualification.",
      "Series: Game of Thrones, F.R.I.E.N.D.S, Breaking Bad, The Boys, The Big Bang Theory",
      "Terms of the Quiz: PRELIMINARY ROUND, MERRY-GO ROUND, KNOCK-OUT ROUND, RAPID-FIRE ROUND",
      "Registration fee is Rs. 150/-",
      "COORDINATORS: Ashmitha (4th Year)-7598588115, Vishnou Prasad (3rd Year)-8807760716, Arvind (3rd Year)-9361080414",
    ],
  },
  {
    title: "Movie Quiz",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSf4IsP48e97Rk5QJy9ltvtZdcyw062wDHpFtfG2O3C1kg6Cjg/viewform?usp=sf_link",
    company_name: "Test your cinematic knowledge and win exciting prizes!",
    icon: m,
    iconBg: "#fff",
    date: "05/10/2023 - 02:30 PM",
    points: [
      "3 Members per Team",
      "Questions will be asked from Hollywood and Kollywood only",
      "There will be 4 rounds - 2 written rounds, 1 dumb charades round and 1 final round. Only the final round questions have negative points for wrong answers.",
      " In each round, the lowest scoring teams will be eliminated and the rest will qualify to the next round.",
      "Registration fee is Rs. 150.",
      "Coordinators: S.VIGNESH - 9345136774, AKSHAY S - 9345424939, TERANCE - 9384363070",
    ],
  },
  {
    title: "Treasure Hunt",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSfJ3hwPWaTV56jx4s5FQTOG-jMeDhTBuiB3WQFDeOAr4lPqUA/viewform?usp=sf_link",
    company_name: "Exciting adventure, clues, and treasures await in this thrilling quest",
    icon: t,
    iconBg: "#fff",
    date: "05/10/2023 - 11:00 AM",
    points: [
      "3-4 members per team.",
      "Each team will be provided with sheet of clues which points the places where the treasure marks will be painted.",
      "The team members should find the exact location of the treasure marks, and once they find the mark , the team should take a group photo with the mark for the verification process.",
      "There will be time limit for the hunt, and the team who comes earlier before the stipulated time with maximum number of treasure marks will be announced as the winner.",
      "Registration fee is Rs. 300/Team. On-spot registration is also allowed.",
      "COORDINATORS: THIRUMURUGAN NRP - 7708577233, PAVITHRA - 8870492743, Mohamed Jameel Maricar A - 7871631359",
    ],
  },
  {
    title: "Anime Quiz",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSeDeBplAVsjaUspSh0FVrF1UIlCZExJAq0dot3yE9pRx8vZ8g/viewform?usp=sf_link",
    company_name: "Test your knowledge of anime culture in this fun quiz!",
    icon: a,
    iconBg: "#fff",
    date: "05/10/2023 - 10:00 AM",
    points: [
      "3 members per team.",
      "Anime: ONE PIECE, NARUTO, DEATH NOTE, ATTACK ON TITAN, TOKYO REVENGERS, BLACK CLOVERS, HAIKYUU, HUNTER X HUNTER",
      "In each round, the lowest scoring teams will be eliminated, and the rest will qualify to the next round. The number of teams eliminated is based on the total number of participating teams.",
      "There will be 3 rounds",
      "Registration fee is Rs. 150/Team.",
      "COORDINATORS: SK. SOHAIL BASHA(9392649878), DHIVYA DARSHINI(7708719371), Sabitha-9345404837",
    ],
  },
  {
    title: "Photography",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdIktC5y21X9zVu8XPU5JBwzmATXkh8my673IBBFaGmj34IWA/viewform?usp=sf_link",
    company_name: "Capture moments, express creativity, and compete in a visual showcase",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 02:30 PM",
    points: [
      "Individual Event",
      "Only .jpeg and .jpg formats are accepted. The EXIF information for the photograph should be intact.",
      "Submissions will not be accepted once the deadline lapses. Judging will be based on creativity, originality and in accordance to the theme.",
      "Submitted photos must be original, created and/or taken by the contestant. It must not contain any materials owned or controlled by a third party for which you have not obtained a license.",
      " Entries found to be 'PHOTOSHOPPED' will be disqualified. Editing used to create illusions, deceptions and/or manipulations, and the adding and removing of significant elements within the frame is prohibited.",
      "Entry fee for Mobile is Rs.50 and for DSLR is Rs.100.",
      "Coordinators: P. Sai Venkatesh - 9346383895, Sai Likitha - 7993497703, Kandhakumar - 7603809313",
    ],
  },
  {
    title: "Pushup Challenge",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSeHFlX6PAdvhrF1tp0y-asEZyYv3JGEFUIL6na1nfFi6iwDQw/viewform?usp=sf_link",
    company_name: "Compete in a high-intensity pushup challenge for fitness supremacy!",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 11:00 AM",
    points: [
      "A team can contain a maximum of three participants",
      "Get down on all fours, placing your hands slightly wider than your shoulders.",
      "Straighten your arms and legs. Lower your body until your chest nearly touches the floor. Pause, then push yourself back up.",
      " Winners will be declared based the count.",
      "Registration fee is Rs. 50.",
      "COORDINATORS: Shanmukha rao-7735285216, Farid-6381552549",
    ],
  },
  {
    title: "Lyric Finding",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScXYTK-NxFV9yPzzkERqHndKNCCj0Scn5cu9p0AwfMX9yPQ3A/viewform?usp=sf_link",
    company_name: "Test your lyrical knowledge with music-themed challenges",
    icon: l,
    iconBg: "#fff",
    date: "05/10/2023 - 10:00 AM",
    points: [
      "3 members per team.",
      "Songs will be in mix of languages",
      "There will two rounds .",
      "For the first round, each team will be given 3 songs with time limit and the top six will be selected for the final round",
      "The second round will be rapid fire with 6 songs and the top three team will be the winners.",
      "Registration fee is Rs. 150/team.",
      "Coordinators: Manoj S - 9360231583, Priyadharshini M - 9952179635, Priyadharshini - 9943469229",
    ],
  },
  {
    title: "IPL auction",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdhRJkW5BT_r2Sv4NRjGjmfsfCVw5VFgBXRIUT4hDYnvSh4qQ/viewform?usp=sf_link",
    company_name: "High-stakes cricket talent acquisition and bidding spectacle.",
    icon: i,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Each Team should consist maximum of  4 members , All team members should be from same college.",
      " Total number of teams is 20. Entries will be closed after that.",
      "First round :     Each team will be given a set of question paper containing 25 MCQs related to cricket.",
      "Second round: Auction round.",
      "Registration fee is Rs. 200/team.",
      "COORDINATORS: MADESH VARADHAN-7499225514, DANAPRASAD M-9487046805",
    ],
  },
]

const literary = [
  {
    title: "Just a min",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScD75i8tSH8gTA1UdDxD_bvXjB1oHpph-m2hO06ABUc3go_bg/viewform?usp=sf_link",
    company_name: "Just a Minute to Make a Difference",
    icon: j,
    iconBg: "#fff",
    date: "04/10/2023 - 02:00 PM",
    points: [
      "Individual Event",
      "Two Rounds in Total( 3minutes for each)",
      "A minute of Self - introduction, A minute to prepare on a topic  picked up by him/her, A minute to speak on the same.",
      "Registration fee is Rs. 50/-",
      "COORDINATORS: Aarthe R S.-9566643429, Nivedha  P -8438737345, Bhuvaneshwari S - 8682079148",
    ],
  },
  {
    title: "Pot Pourri",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSeoPHPhcUMtvZfnCIVZSB3bLlwhBZxpS2p1dcneyQ93an-MSQ/viewform?usp=sf_link",
    company_name: "Mix of surprises and delights for everyone.",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 10:00 AM",
    points: [
      "3 members per team.",
      "Total Three Rounds",
      "Round 1: ACT IT OUT. Round 2: PICTIONARY ROUND. Round 3: TRACK ME",
      "Registration fee is Rs. 150 per Team",
      "COORDINATORS:thilagavathi anu, Vinodhini.J (3rd year ECE) - 9791082670",
    ],
  },
  {
    title: "whats the climax",
    link:"https://forms.gle/JLskinkrZUCpjctcA",
    company_name: " Unforgettable, thrilling, and suspense-filled grand finale.",
    icon: w,
    iconBg: "#fff",
    date: "05/10/2023 - 02:00 PM",
    points: [
      "INDIVIDUAL EVENT",
      "Participants will step into the shoes of an author or director in this engaging written event.",
      "They'll be presented with a captivating story and tasked with crafting their own climactic endings.",
      "Whether they choose to evoke tears or send shivers down spines, the stage is theirs to command.",
      "Registration fee is Rs. 50.",
      "Coordinators: Hrithin -8156881685, Nivedha P - 8438737345",
    ],
  },
  {
    title: "If things had Life",
    link:"https://forms.gle/aGcgKfjEiyTnxiJJ6",
    company_name: "Explore science through captivating cinematic experiences.",
    icon: i,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Indivdual event",
      "The participants are assigned an inanimate object (non-living thing) and asked to deliver a short speech from the perspective of that object, embodying its thoughts, emotions, and experiences.",
      "Registration fee is Rs. 50.",
      "COORDINATORS: Harshal Kariya : 7020694766, Thilagavathianu : 9360483503",
    ],
  },
  {
    title: "Sell me a pen",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdEB5hohCHIatraLGR3TKd03yP6MzEyZTw8WXxyaUqV2sjg-Q/viewform?usp=sf_link",
    company_name: "Pitch your persuasive skills",
    icon: s,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Solo event.",
      "The participant is given a commodity to sell and has to convince the customer (read, judges) to buy it.",
      "Preparation Time 3 MINUTES. Duration- 5 minutes",
      "Registration fee is Rs. 50",
      "Coordinators: Shreyasi Majumder-9563587416, kailash S-6385687148, Reena MD",
    ],
  },
]

const cultural = [
  {
    title: "Variety Variety - Classical Solo",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSd0AUYgsMWaBW21zKv64_Gt1h92cVLqqoGN-FvqB_YG0wHC7Q/viewform?usp=sf_link",
    company_name: "Experience a diverse classical solo showcase in music, dance, and more.",
    icon: v,
    iconBg: "#fff",
    date: "05/10/2023 - 9:30 AM",
    points: [
      "The solo performance can be anything (dancing, singing, Instrumental etc...).",
      " Duration for each performance 3 to 4 minutes.",
      "The theme is open, but it should not be abusive, any political issue or hurt any religious view. Otherwise participation will be disqualified. No lighters, cigarettes are allowed.",
      "The Required materials should be brought by the participants themselves. If participants have audio file should be submitted at the starting of the event itself only after final checking.",
      "Registration fee is Rs. 150.",
      "CO-ORDINATORS: DHINESHKUMAR G (8220557900), PRATIKSHA R (9360871181), PRAVEENE R (8438778446)",
    ],
  },
  // {
  //   title: "Variety Variety - Western Solo",
  //   link:"#",
  //   company_name: "small discrip",
  //   icon: fifa,
  //   iconBg: "#fff",
  //   date: "04/10/2023 - 09:30 AM",
  //   points: [
  //     "Solo event. 1v1.",
  //     "The match will be played on playstation.Only Knockout stages. Normal kickoff >>> Extra time >>> penalty shootout",
  //     "The match duration will be informed on the day of tournament.",
  //     "Registration fee is Rs. 150.",
  //     "Coordinators:  9600224229",
  //   ],
  // },
  {
    title: "Adapt Tunes",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSfN4LFeNjCkrg2maJrLBaQjcerOCmJqGB3NFPXpqE77Os8TyQ/viewform?usp=sf_link",
    company_name: "Dance to evolving musical rhythms.",
    icon: a,
    iconBg: "#fff",
    date: "04/10/2023 - 02:30 PM",
    points: [
      "Solo event.",
      "Duration - 3 minutes.",
      "Four to six songs will be played on spot.",
      "Registration fee is Rs. 200",
      "Coordinators: Jayraj Pozhilan V - 9486901377, Apurva - 6207227172, Gowtham Balaji -  9150313640",
    ],
  },
  {
    title: "Variety Variety - Group",
    link:"https://forms.gle/2GLzh1kFZ85Jiv4C6",
    company_name: "A diverse and entertaining event for all",
    icon: v,
    iconBg: "#fff",
    date: "05/10/2023 - 02:00 PM",
    points: [
      "The group performance can be anything (dancing, singing, Instrumental etc...).",
      "Duration for each performance 3 to 4 minutes.",
      "The theme is open, but it should not be abusive, any political issue or hurt any religious view. Otherwise participation will be disqualified.",
      "No lighters, cigarettes are allowed. The Required materials should be brought by the participants themselves. If participants have audio file should be submitted at the starting of the event itself only after final checking.",
      "Registration fee is Rs. 300.",
      "Coordinators: Nandhini P-7598514122, Janvi - 9422925547, Yuvashri devi-9443383090",
    ],
  },
]

const esports = [
  {
    title: "Fifa",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdhQeKXCSR-qmLK5_GQtP2puC4S66oVwjQZsIpebxfr5Qq99g/viewform?usp=sf_link",
    company_name: "FIFA gaming tournament for enthusiasts.",
    icon: f,
    iconBg: "#fff",
    date: "04/10/2023 - 02:30 PM",
    points: [
      "Solo event. 1v1.",
      "The match will be played on playstation.Only Knockout stages. Normal kickoff >>> Extra time >>> penalty shootout",
      "The match duration will be informed on the day of tournament.",
      "Registration fee is Rs. 100.",
      "Coordinators: Coordinators: Hrithin-8156881685, Arvindraj J-9600224229",
    ],
  },
  {
    title: "Valorant",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSfFDJ_t6XSoC0rtBus8tT2FgNxfo_ympm25S7AFclSe7nhtYA/viewform?usp=sf_link",
    company_name: "Valorant showdown: tactical battles await",
    icon: v,
    iconBg: "#fff",
    date: "04/10/2023 - 07:00 PM",
    points: [
      "Game mode: Deathmatch",
      "Three map will be played for whole tournament. Gun will be selected in respect to the majority",
      "Fixture and timings will be displayed in discord server on morning of the tournament day.",
      "Series of 3 games take place every player will be given points according to the position secured(1st position -10points/10th position -1 point)",
      "Registration fee is Rs. 150/head.",
      "Coordinators:  9600224229",
    ],
  },
  {
    title: "Mini Militia",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSck51zGKOEyU4gkkVsQ71eOSZG1AQxJDMONS6gfUNApAlVINQ/viewform?usp=sf_link",
    company_name: "Competitive gaming with intense multiplayer battles.",
    icon: m,
    iconBg: "#fff",
    date: "05/10/2023 - 03:00 PM",
    points: [
      "Maximum four and minimum three members per team are allowed.",
      "All round are knock-out matches. Win and move on to the next round.",
      "All are requested to be in classroom 5 minutes in advance to make sure of hotspot connectivity.",
      "Entry fee: Rs. 50 per head",
      "Coordinators: Vijayapithagaran 6381961491, Kavimani 8903408160",
    ],
  },
  {
    title: "BGMI",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScSwkbY6vSmQhISCVm3EwK3V8m_IfHhEsxdO4u-uji30N1hUA/viewform?usp=sf_link",
    company_name: " Battle for Victory!",
    icon: b,
    iconBg: "#fff",
    date: "05/10/2023 - 07:00 PM",
    points: [
      "4 Players per Team",
      "Event will be conducted online(Participants can play from their home).",
      "Room Id and Password will be sent to the participants.",
      "Players should carry their own device with the game installed.",
      "If a player found using hacks, the respective team will be disqualified.",
      "Entry fee: Rs. 200 per head",
      "Coordinators: ",
    ],
  },
]

const day1 = [

  {
    title: "Circuit Debugging",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSegjy9Vf1Iza4q_KdqNlomM05JaEvYNVt6s-TeIpHwChh5Phw/viewform?usp=sf_link",
    company_name: "Identify and fix electrical faults",
    icon: c,
    iconBg: "#fff",
    date: "04/10/2023 - 02:00 PM",
    points: [
      "A team can contain a maximum of three participants",
      "The event has three rounds which test your circuit debugging skills. ",
      "Prerequisite: basics of analog and digital electronics, op amp, ic555, multsim simulator.",
      "Registration fee is Rs. 150.",
      "COORDINATORS: Sree Teja (7989291343), kalaimathi (9345831705), Ganja Yuvarani (9493724523)",
    ],
  },
  {
    title: "Just a min",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScD75i8tSH8gTA1UdDxD_bvXjB1oHpph-m2hO06ABUc3go_bg/viewform?usp=sf_link",
    company_name: "Just a Minute to Make a Difference",
    icon: j,
    iconBg: "#fff",
    date: "04/10/2023 - 02:00 PM",
    points: [
      "Individual Event",
      "Two Rounds in Total( 3minutes for each)",
      "A minute of Self - introduction, A minute to prepare on a topic  picked up by him/her, A minute to speak on the same.",
      "Registration fee is Rs. 50/-",
      "COORDINATORS: Aarthe R S.-9566643429, Nivedha  P -8438737345, Bhuvaneshwari S - 8682079148",
    ],
  },
  {
    title: "Tech Quiz",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdgaTV_8WIB_etM1fxO9uRDD-llzkJ2NlFx8mbJ6WPe3asK1A/viewform?usp=sf_link",
    company_name: "Test your tech knowledge skills",
    icon: t,
    iconBg: "#fff",
    date: "04/10/2023 - 02:30 PM",
    points: [
      "A team can contain a maximum of three participants",
      "Consists of three rounds.",
      "A general technical quiz.",
      "Registration fee is Rs. 100/team.",
      "COORDINATORS: BARATH KUMAR.M (+91 63822 82725), LAKSHMI NARAYANA PERUMAL.S (+91 77083 94526), KAILASH.S (+91 6385 687 148), ARVIND.A +91 93610 80414)",
    ],
  },
  {
    title: "Adapt Tunes",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSfN4LFeNjCkrg2maJrLBaQjcerOCmJqGB3NFPXpqE77Os8TyQ/viewform?usp=sf_link",
    company_name: "Dance to evolving musical rhythms.",
    icon: a,
    iconBg: "#fff",
    date: "04/10/2023 - 02:30 PM",
    points: [
      "Solo event.",
      "Duration - 3 minutes.",
      "Four to six songs will be played on spot.",
      "Registration fee is Rs. 200",
      "Coordinators: Jayraj Pozhilan V - 9486901377, Apurva - 6207227172, Gowtham Balaji -  9150313640",
    ],
  },
  {
    title: "Fifa",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdhQeKXCSR-qmLK5_GQtP2puC4S66oVwjQZsIpebxfr5Qq99g/viewform?usp=sf_link",
    company_name: "FIFA gaming tournament for enthusiasts.",
    icon: f,
    iconBg: "#fff",
    date: "04/10/2023 - 02:30 PM",
    points: [
      "Solo event. 1v1.",
      "The match will be played on playstation.Only Knockout stages. Normal kickoff >>> Extra time >>> penalty shootout",
      "The match duration will be informed on the day of tournament.",
      "Registration fee is Rs. 100.",
      "Coordinators: Hrithin-8156881685, Arvindraj J-9600224229",
    ],
  },
  {
    title: "Chess",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdWN2qrHMj7DyiXgK2_SbjFtQrfnKmVTzUyr0L935hi5n9PTw/viewform?usp=sf_link",
    company_name: "Chess tournament for strategic minds.",
    icon: c,
    iconBg: "#fff",
    date: "04/10/2023 - 02:30 PM",
    points: [
      "Solo event. 1v1.",
      "There will be 10 mins time limit for each player. No increment for time after each move",
      "Every match will be elimination match",
      "If stalemate/draw occurs there will be tie breaker for each player with 5 mins each.",
      "The registration amount is Rs. 75 per member",
      "COORDINATORS: SAKTHIDHARSHAN M- 8220855421, MURALIDHARAN B-9047085058, HARIHARAN GV - 9629231402",
    ],
  },
  {
    title: "Valorant",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSfFDJ_t6XSoC0rtBus8tT2FgNxfo_ympm25S7AFclSe7nhtYA/viewform?usp=sf_link",
    company_name: "Valorant showdown: tactical battles await",
    icon: v,
    iconBg: "#fff",
    date: "04/10/2023 - 07:00 PM",
    points: [
      "Game mode: Deathmatch",
      "Three map will be played for whole tournament. Gun will be selected in respect to the majority",
      "Fixture and timings will be displayed in discord server on morning of the tournament day.",
      "Series of 3 games take place every player will be given points according to the position secured(1st position -10points/10th position -1 point)",
      "Registration fee is Rs. 150/head.",
      "Coordinators:  9600224229",
    ],
  },
];



const day2 = [
  {
    title: "Paper Presentation",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScAZBLjimWg2_LrF1JW193gFuUUCs1K98VQqKHQ5zaDcO9pxA/viewform?usp=sf_link",
    company_name: "Showcase research and ideas eloquently.",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 10:00 AM",
    points: [
      "A team can contain a maximum of three participants",
      "The selected team should come with the hard copy of their abstracts ",
      "Presentation time is 10 to 15 minutes",
      "Registration fee is Rs. 50.",
      "COORDINATORS: ANURAGAA S (6381278692), THIRUMURUGAN S(9629701158), SWARUP(6309086433)",
    ],
  },
  {
    title: "Treasure Hunt",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSfJ3hwPWaTV56jx4s5FQTOG-jMeDhTBuiB3WQFDeOAr4lPqUA/viewform?usp=sf_link",
    company_name: "Exciting adventure, clues, and treasures await in this thrilling quest",
    icon: t,
    iconBg: "#fff",
    date: "05/10/2023 - 11:00 AM",
    points: [
      "3-4 members per team.",
      "Each team will be provided with sheet of clues which points the places where the treasure marks will be painted.",
      "The team members should find the exact location of the treasure marks, and once they find the mark , the team should take a group photo with the mark for the verification process.",
      "There will be time limit for the hunt, and the team who comes earlier before the stipulated time with maximum number of treasure marks will be announced as the winner.",
      "Registration fee is Rs. 300/Team. On-spot registration is also allowed.",
      "COORDINATORS: THIRUMURUGAN NRP - 7708577233, PAVITHRA - 8870492743, Mohamed Jameel Maricar A - 7871631359",
    ],
  },
  {
    title: "Anime Quiz",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSeDeBplAVsjaUspSh0FVrF1UIlCZExJAq0dot3yE9pRx8vZ8g/viewform?usp=sf_link",
    company_name: "Test your knowledge of anime culture in this fun quiz!",
    icon: a,
    iconBg: "#fff",
    date: "05/10/2023 - 10:00 AM",
    points: [
      "3 members per team.",
      "Anime: ONE PIECE, NARUTO, DEATH NOTE, ATTACK ON TITAN, TOKYO REVENGERS, BLACK CLOVERS, HAIKYUU, HUNTER X HUNTER",
      "In each round, the lowest scoring teams will be eliminated, and the rest will qualify to the next round. The number of teams eliminated is based on the total number of participating teams.",
      "There will be 3 rounds",
      "Registration fee is Rs. 150/Team.",
      "COORDINATORS: SK. SOHAIL BASHA(9392649878), DHIVYA DARSHINI(7708719371), Sabitha-9345404837",
    ],
  },
  {
    title: "Lyric Finding",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScXYTK-NxFV9yPzzkERqHndKNCCj0Scn5cu9p0AwfMX9yPQ3A/viewform?usp=sf_link",
    company_name: "Test your lyrical knowledge with music-themed challenges",
    icon: l,
    iconBg: "#fff",
    date: "05/10/2023 - 10:00 AM",
    points: [
      "3 members per team.",
      "Songs will be in mix of languages",
      "There will two rounds .",
      "For the first round, each team will be given 3 songs with time limit and the top six will be selected for the final round",
      "The second round will be rapid fire with 6 songs and the top three team will be the winners.",
      "Registration fee is Rs. 150/team.",
      "Coordinators: Manoj S - 9360231583, Priyadharshini M - 9952179635, Priyadharshini - 9943469229",
    ],
  },
  {
    title: "Pot Pourri",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSeoPHPhcUMtvZfnCIVZSB3bLlwhBZxpS2p1dcneyQ93an-MSQ/viewform?usp=sf_link",
    company_name: "Mix of surprises and delights for everyone.",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 10:00 AM",
    points: [
      "3 members per team.",
      "Total Three Rounds",
      "Round 1: ACT IT OUT. Round 2: PICTIONARY ROUND. Round 3: TRACK ME",
      "Registration fee is Rs. 150 per Team",
      "COORDINATORS:thilagavathi anu, Vinodhini.J (3rd year ECE) - 9791082670",
    ],
  },
  {
    title: "Variety Variety - Classical Solo",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSd0AUYgsMWaBW21zKv64_Gt1h92cVLqqoGN-FvqB_YG0wHC7Q/viewform?usp=sf_link",
    company_name: "Experience a diverse classical solo showcase in music, dance, and more.",
    icon: v,
    iconBg: "#fff",
    date: "05/10/2023 - 9:30 AM",
    points: [
      "The solo performance can be anything (dancing, singing, Instrumental etc...).",
      " Duration for each performance 3 to 4 minutes.",
      "The theme is open, but it should not be abusive, any political issue or hurt any religious view. Otherwise participation will be disqualified. No lighters, cigarettes are allowed.",
      "The Required materials should be brought by the participants themselves. If participants have audio file should be submitted at the starting of the event itself only after final checking.",
      "Registration fee is Rs. 150.",
      "CO-ORDINATORS: DHINESHKUMAR G (8220557900), PRATIKSHA R (9360871181), PRAVEENE R (8438778446)",
    ],
  },
  {
    title: "Pushup Challenge",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSeHFlX6PAdvhrF1tp0y-asEZyYv3JGEFUIL6na1nfFi6iwDQw/viewform?usp=sf_link",
    company_name: "Compete in a high-intensity pushup challenge for fitness supremacy!",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 11:00 AM",
    points: [
      "A team can contain a maximum of three participants",
      "Get down on all fours, placing your hands slightly wider than your shoulders.",
      "Straighten your arms and legs. Lower your body until your chest nearly touches the floor. Pause, then push yourself back up.",
      " Winners will be declared based the count.",
      "Registration fee is Rs. 50.",
      "COORDINATORS:Shanmukha rao-7735285216, Farid-6381552549",
    ],
  },
  {
    title: "Technical connexion",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSfkddi7Q_C8-pb_ZQjryO0OdQqPH6o0GgzfUsnROKu-jXZfxQ/viewform?usp=sf_link",
    company_name: "Explore tech's impact through innovative connections.",
    icon: t,
    iconBg: "#fff",
    date: "05/10/2023 - 11:00 AM",
    points: [
      "A team can consist of two members.",
      "Three Rounds will be Conducted. ",
      "First round : Written round. Second round: Questions will be displayed and the teams should answer it within 30 seconds.",
      "Third round:  Indirect clues will be given one by one and the teams should find the technical word behind it.",
      "Registration fee is Rs. 100/-.",
      "COORDINATORS: PARIMALA DEVI(8807342948), SHAMEER AHMED(6374636031), SATISH KUMAR(6383718465), PRAVEEN P(6385451354)",
    ],
  },
  {
    title: "Triad (Googler, Electric Fence,snippet shuffle)",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSf1HngbWA1kAhDGNP5qeYgM40H5_6j5YbjIJmDnrkE0yc70oQ/viewform?usp=sf_link",
    company_name: "Fun Fun Fun - Three ways",
    icon: t,
    iconBg: "#fff",
    date: "05/10/2023 - 02:00 PM",
    points: [
      "A team can consist of two members.",
      "It is a collection of three fun events.",
      "Part 1: GOOGLER, Part 2: SNIPPET SHUFFLE, Part 3: ELECTRIC FENCE",
      "Registration fee is Rs. 100/-",
      "COORDINATORS:  CH VENKATA UPENDRA(8985122204), YUVARANI V D(7695981434), SHEFAOUDEEN Z(9361030025), SHAANTHAPRIYAN B",
    ],
  },
  {
    title: "Programming dating",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdgaTV_8WIB_etM1fxO9uRDD-llzkJ2NlFx8mbJ6WPe3asK1A/viewform?usp=sf_link",
    company_name: "Where Love Meets Logic.",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 02:00 PM",
    points: [
      "A team can consist of two members.",
      "A female coder is partnered with a male programmer they have to go on programming date which should be technical..",
      "Registration fee is Rs. 150/team.",
      "COORDINATORS: SANGESH S(8870073053), MANJUNNATH, SIVABHARATH K",
    ],
  },
  {
    title: "whats the climax",
    link:"https://forms.gle/JLskinkrZUCpjctcA",
    company_name: " Unforgettable, thrilling, and suspense-filled grand finale.",
    icon: w,
    iconBg: "#fff",
    date: "05/10/2023 - 02:00 PM",
    points: [
      "INDIVIDUAL EVENT",
      "Participants will step into the shoes of an author or director in this engaging oral event.",
      "They'll be presented with a captivating story and tasked with crafting their own climactic endings.",
      "Whether they choose to evoke tears or send shivers down spines, the stage is theirs to command.",
      "Registration fee is Rs. 50.",
      "Coordinators: Hrithin -8156881685, Nivedha P - 8438737345",
    ],
  },
  {
    title: "Variety Variety - Group",
    link:"https://forms.gle/2GLzh1kFZ85Jiv4C6",
    company_name: "A diverse and entertaining event for all",
    icon: v,
    iconBg: "#fff",
    date: "05/10/2023 - 02:00 PM",
    points: [
      "The group performance can be anything (dancing, singing, Instrumental etc...).",
      "Duration for each performance 3 to 4 minutes.",
      "The theme is open, but it should not be abusive, any political issue or hurt any religious view. Otherwise participation will be disqualified.",
      "No lighters, cigarettes are allowed. The Required materials should be brought by the participants themselves. If participants have audio file should be submitted at the starting of the event itself only after final checking.",
      "Registration fee is Rs. 300.",
      "Coordinators: Nandhini P-7598514122, Janvi - 9422925547, Yuvashri devi-9443383090",
    ],
  },
  {
    title: "Movie Quiz",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSf4IsP48e97Rk5QJy9ltvtZdcyw062wDHpFtfG2O3C1kg6Cjg/viewform?usp=sf_link",
    company_name: "Test your cinematic knowledge and win exciting prizes!",
    icon: m,
    iconBg: "#fff",
    date: "05/10/2023 - 02:30 PM",
    points: [
      "3 Members per Team",
      "Questions will be asked from Hollywood and Kollywood only",
      "There will be 4 rounds - 2 written rounds, 1 dumb charades round and 1 final round. Only the final round questions have negative points for wrong answers.",
      " In each round, the lowest scoring teams will be eliminated and the rest will qualify to the next round.",
      "Registration fee is Rs. 150.",
      "Coordinators: S.VIGNESH - 9345136774, AKSHAY S - 9345424939, TERANCE - 9384363070",
    ],
  },
  {
    title: "Photography",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdIktC5y21X9zVu8XPU5JBwzmATXkh8my673IBBFaGmj34IWA/viewform?usp=sf_link",
    company_name: "Capture moments, express creativity, and compete in a visual showcase",
    icon: p,
    iconBg: "#fff",
    date: "05/10/2023 - 02:30 PM",
    points: [
      "Individual Event",
      "Only .jpeg and .jpg formats are accepted. The EXIF information for the photograph should be intact.",
      "Submissions will not be accepted once the deadline lapses. Judging will be based on creativity, originality and in accordance to the theme.",
      "Submitted photos must be original, created and/or taken by the contestant. It must not contain any materials owned or controlled by a third party for which you have not obtained a license.",
      " Entries found to be 'PHOTOSHOPPED' will be disqualified. Editing used to create illusions, deceptions and/or manipulations, and the adding and removing of significant elements within the frame is prohibited.",
      "Entry fee for Mobile is Rs.50 and for DSLR is Rs.100.",
      "Coordinators: P. Sai Venkatesh - 9346383895, Sai Likitha - 7993497703, Kandhakumar - 7603809313",
    ],
  },
  {
    title: "Mini Militia",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSck51zGKOEyU4gkkVsQ71eOSZG1AQxJDMONS6gfUNApAlVINQ/viewform?usp=sf_link",
    company_name: " Intense mobile multiplayer action for competitive gamers.",
    icon: m,
    iconBg: "#fff",
    date: "05/10/2023 - 03:00 PM",
    points: [
      "Maximum four and minimum three members per team are allowed.",
      "All round are knock-out matches. Win and move on to the next round.",
      "All are requested to be in classroom 5 minutes in advance to make sure of hotspot connectivity.",
      "Entry fee: Rs. 50 per head",
      "Coordinators: Vijayapithagaran 6381961491, Kavimani 8903408160",
    ],
  },
  {
    title: "BGMI",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScSwkbY6vSmQhISCVm3EwK3V8m_IfHhEsxdO4u-uji30N1hUA/viewform?usp=sf_link",
    company_name: " Battle for Victory!",
    icon: b,
    iconBg: "#fff",
    date: "05/10/2023 - 07:00 PM",
    points: [
      "4 Players per Team",
      "Event will be conducted online(Participants can play from their home).",
      "Room Id and Password will be sent to the participants.",
      "Players should carry their own device with the game installed.",
      "If a player found using hacks, the respective team will be disqualified.",
      "Entry fee: Rs. 200 per head",
      "Coordinators: Deepak Prasad  9059948459, Nishyath 8807843841",
    ],
  },
];



const day3 = [

  {
    title: "Solo Dance",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSf4OtVbJvOTMcfTDH-RqK-vJeZxUVaonctdgmEzy9HCyFCdzw/viewform?usp=sf_link",
    company_name: "Express yourself through solo dance performance.",
    icon: s,
    iconBg: "#fff",
    date: "06/10/2023 - 09:30 AM",
    points: [
      "The solo performance (Dance only).",
      "Duration for each performance 4 to 5 minutes.",
      "The theme is open, but it should not be abusive, any political issue or hurt any religious view. Otherwise participation will be disqualified.",
      "The Required materials should be brought by the participants themselves. If participants have audio file upload now or should be submitted at the starting of the event itself only after final checking.",
      "Registration fee is Rs. 150.",
      "COORDINATORS: Shutharshan-8825521823, Pravin-9361445615, Mohammed Rafiq-8015525317, Akanksha Das-9267907798, Rajavardhini-9500619499",
    ],
  },
  {
    title: "Cinematic Science",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSeFolVc55n1jVilkikRmdO1Fa257bzr8X1ZHeT2uCTe9TDWVw/viewform?usp=sf_link",
    company_name: "Explore science through captivating cinematic experiences.",
    icon: c,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      " A team can consist of two members.",
      "A scene from a movie will be displayed and the participant has to find the scientific concept behind that particular scene and explain about it briefly.",
      "Registration fee is Rs. 100.",
      "COORDINATORS:VIJAYABARATHI J(6380436136), SIVAPRAKASH R(8300159749), TERENCE JONES",
    ],
  },
  {
    title: "Hunt the Code",
    link:"https://forms.gle/u56kqcYgeZ6vDEfb9",
    company_name: "A thrilling code-breaking adventure awaits!",
    icon: h,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Maximum of 2 members per team.",
      "The contest will consist of sets of questions, but with a catch: you will not be given the problem statement for any question. Just the sample inputs and sample outputs. Using just that, you are required to find the logic between the inputs and the outputs and code the program which can give the correct output for the given input. (There will also be hidden testcases)",
      "Registration fee is Rs. 75/Team.",
      "COORDINATORS: T C Adityaa-9944581729, Keerthivasan-8778336814 , Kamalesh-9150431574",
    ],
  },
  {
    title: "Series Quiz",
    link:"https://docs.google.com/forms/d/e/1FAIpQLScvY0Spedrxdt9fqSIfzCIaFi8_KPZyd75THBie2u-hbhY-Sg/viewform?usp=sf_link",
    company_name: "Test your TV show knowledge and win prizes!",
    icon: s,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Maximum three and minimum two members per team are allowed",
      "Every participant must be respectful towards coordinators and other participants.",
      "Any unfair moments will lead you to disqualification.",
      "Series: Game of Thrones, F.R.I.E.N.D.S, Breaking Bad, The Boys, The Big Bang Theory",
      "Terms of the Quiz: PRELIMINARY ROUND, MERRY-GO ROUND, KNOCK-OUT ROUND, RAPID-FIRE ROUND",
      "Registration fee is Rs. 150/-",
      "COORDINATORS: Ashmitha (4th Year)-7598588115, Vishnou Prasad (3rd Year)-8807760716, Arvind (3rd Year)-9361080414",
    ],
  },
  {
    title: "IPL auction",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdhRJkW5BT_r2Sv4NRjGjmfsfCVw5VFgBXRIUT4hDYnvSh4qQ/viewform?usp=sf_link",
    company_name: "High-stakes cricket talent acquisition and bidding spectacle",
    icon: i,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Each Team should consist maximum of  4 members , All team members should be from same college.",
      " Total number of teams is 20. Entries will be closed after that.",
      "First round :     Each team will be given a set of question paper containing 25 MCQs related to cricket.",
      "Second round: Auction round.",
      "Registration fee is Rs. 200/team.",
      "COORDINATORS: MADESH VARADHAN-7499225514, DANAPRASAD M-9487046805",
    ],
  },
  {
    title: "Sell me a pen",
    link:"https://docs.google.com/forms/d/e/1FAIpQLSdEB5hohCHIatraLGR3TKd03yP6MzEyZTw8WXxyaUqV2sjg-Q/viewform?usp=sf_link",
    company_name: "Pitch your persuasive skills",
    icon: s,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Solo event.",
      "The participant is given a commodity to sell and has to convince the customer (read, judges) to buy it.",
      "Preparation Time 3 MINUTES. Duration- 5 minutes",
      "Registration fee is Rs. 50",
      "Coordinators: Shreyasi Majumder-9563587416, kailash S-6385687148, Reena MD",
    ],
  },
  {
    title: "If things had Life",
    link:"https://forms.gle/aGcgKfjEiyTnxiJJ6",
    company_name: "Explore science through captivating cinematic experiences.",
    icon: i,
    iconBg: "#fff",
    date: "06/10/2023 - 10:00 AM",
    points: [
      "Indivdual event",
      "The participants are assigned an inanimate object (non-living thing) and asked to deliver a short speech from the perspective of that object, embodying its thoughts, emotions, and experiences.",
      "Registration fee is Rs. 50.",
      "COORDINATORS: Harshal Kariya : 7020694766, Thilagavathianu : 9360483503",
    ],
  },
  
];



export { day1,day2,day3,technical,nontechnical,literary,cultural,esports };
